spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
adapters:
  clients:
    aws:
      name: AWS adapter
      host: localhost
      port: 8081
      costLimit: 3000.00
      cronExpression: 0 0 3 * * *